# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MWX0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000XWM
# MWOc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,l0WM
# MMW0l,,,:cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc;,',lKWMM
# MMMWKo,,:x0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OO0KKKKKKKK0Ok0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOo;,;oXMMMM
# MMMMMXd;,:d0KKKKKKKKKKKKKK0KKKKOxk0K00K0Oko::loxO00kool:;ldxkOOOOkxk0KKKKKKKKKKKKKKKKKKKOl,';xNMMMMM
# MMMMMMNx;';d0KKKKKKKK0Okxolx00Oo,;clld00o;;,,;,;xOkl,;:,,:;,od:::;,;oxk0kooxk00KKKKKKKKkc,,:kNMMMMMM
# MMMMMMMNk:,;oOKKK0kddoccc;,:ddl:,'';lx0Ol,,,',,,lxxl,;;,,;;;dkc,cdl;,;dkl;;:ccloxO0KKKkc,,:OWMMMMMMM
# MMMMMMMMWOc,,lOKKOl,;c:;::,,:dxc,;c:::oxxl;,:c;:dOOkdd:,,coool;,okd;;dko;;:::;,;;ckK0x:,,c0WMMMMMMMM
# MMMMMMMMMW0l,,ckKKkc,;:,,,;:,coccx00kdxOKklldxdodkkkkxoclx00xlcccc;,;oo:;::;;::::d00d;,,lKWMMMMMMMMM
# MMMMMMMMMMWKo,,:x0Kkc,;;;';lllxkO0KKKKOkxl'..............,oxk000OOkxddoc;;;;,:c:o00o;,;oXMMMMMMMMMMM
# MMMMMMMMMMMMXd;,;d0Kkc;coodO00KKKK0koo:....              ...'codkKKKKK0Okdoc:;:o0Oo,,;xNMMMMMMMMMMMM
# MMMMMMMMMMMMMNx:,;oOKOxdooooooooool,...                      ...;ooooooooooldxxOkl,':kNMMMMMMMMMMMMM
# MMMMMMMMMMMMMMWO:,,lOK0c...........                             ............cOKkc,,:OWMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMW0c,,ck0kdd:'....          ................          ....'cddk0x:,,c0WMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMWKl,,:x0KKOxxxc.        ..'okkkkkkkkkkkkl..         .cxxx0KK0d:,,lKWMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMXo;,:d0Kd;''..       .,ox0KK0kl::lk0KKOxc.        ..'';xK0d;,;oXWMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMXd;,;oOxcccc:,. .;'..:OKKOd:..  ..:oOKKx' .,;. .,:c:clkOo;';xXMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMNk:,;oOKKKKKo. ,xc..:OK0xol;.  .;lox0Kx' 'dx' 'dKKKKKOl,,:kNMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMWO:,,lkKKKKo..,xc..:OK0xl:'.  .,cdOKKx' .dx' .dKKKKkc,,:OWMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMW0c,,ck000o. ,xc..:Od;..        .'lOx' .dx' .d000x:,,c0WMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMWKo,,;;;,'..,xc..,:.             .;:. .dx' .';;;;,,lKWMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMXd;''','. ,xc. .                 .  .dx' .',''';oXMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMNx;';lc. ,xc...;;'. ..;;:,. ..;:,. .dx' .oo;';dXMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMNk:,,,. ,xc. .',.. ..,,,..  .','. .dx' .,,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc,'..'llc:;'....';:cc:,'......':ll'..',:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l,',o0K0OkxdxkOOOOkkOOOkkxxxxxOOOd;',c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,,;c:;,,,;::c:;;::;;:cccc:;;;;:;,,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;'',lkkkxxxxxxkkkkxxdooodxkd:,,;oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;,,ldolcllooc::::lodddolllc;';dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:,,,;odxxdddxxxkkxdooodc,,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc,,:dxddddoc::ccodxddoc,,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl,,,,:ooodxkkxxoloo:,',c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,',lxxddollodxxdo:,,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;',,:loodddool;'';oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;,,cxkdoooddl;,;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:,,,;cllc;,,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c,';xXN0c,,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl,,;ldc,,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;,,'',lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;,';oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

print('Hello World')