
# MMMMMMMMMMMMMMXddKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKddXMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMNo,l0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l'lXMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMNd;xXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXx;oNMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMXl;0K0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKK0;cXMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMx.oXkKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKOXo.dMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMk.:XOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0OK:.xMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMk.;KOOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO0K;.xMMMMMMMMMMMMMMMMMMMMM
# MMMMNKKNMMMMMMMMMk.:KOkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOOK:.xMMMMMMMMMNKKNMMMMMMMM
# MMMWOO00WMMMMMMMMk'lXOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOXl.xMMMMMMMMWK0OOWMMMMMMM
# MMMWddKKNMMMMMMMWo.dXxOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0kXd.oNMMMMMMMNKKooNMMMMMMM
# MMMMx;kKKWMMMMMM0,'k0d0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKd0k',0MMMMMMWKKk,dWMMMMMMM
# MMMMK:'oONMMMMNO:.,OkdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdkO,.:ONMMMMNOo';KMMMMMMMM
# MMMMMO,.'cxOOxc...;OkxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxkO;...cxOOxc'.,kWMMMMMMMM
# MMMMMW0c,'......,:cOOkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOOO:,'......',cOWMMMMMMMMM
# MMMMMMWKd,......:l;xOkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkOk::;......,oKWMMMMMMMMMM
# MMMMMMMMW0l,....':,lOkKMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMKkOxcl;  ..,lONMMMMMMMMMMMM
# MN00XWMMMMWXkl,..,dx0OOWMMMMMMMMMMMMMMMMXkkXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXkkXMMMMMMMMMMMMMMMMWOO0xo'  .lkXWMMMMMN0ONMMMMM
# MKclOOXMMMMMMWXx;.:ddOO0WMMMMMMMMMMMMMMMWOloO00NMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWXXWMMMMMMMMMMMMMMMMMMMMMMMMMMNK0OockWMMMMMMMMMMMMMMMW0OOdx:.;dKWMMMMMMX0Olc0MMMMM
# MNo,okOXWMMMMMMMXl':;:kO0NMMMMMMMMMMMMMMMWKolO0kXMMMMMMMMMMMMMMMMMMMMMMMMW0xKN0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0NKx0WMMMMMMMMMMMMMMMMMMMMMMMMXO0Oll0WMMMMMMMMMMMMMMMW0Ok:;:'cKMMMMMMMWX0ko,oNMMMMM
# MMXl',lkKNNWMMMWOc';;.,kK0NMMMMMMMMMMMMMMMM0cl000WMMMMMMMMMMMMMMMMMMMMMMM0oONO0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ONOlOWMMMMMMMMMMMMMMMMMMMMMMW00KocOWMMMMMMMMMMMMMMMNKKk,.;;':kWMMMWWNKkl,.cKMMMMMM
# MMMXo...:loxxxdc'..cOc .o0KXWMMMMMMMMMMMMMMWk:dK0XMMMMMMMMMMMMMMMMMMMMMMKllKKkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkKKclKMMMMMMMMMMMMMMMMMMMMMMX0Xk:xWMMMMMMMMMMMMMMWNX0o. .::..'cdxxxol:...lXMMMMMMM
# MMMMWOc.............;ol,.;xKXNWMMMMMMMMMMMMMK:;OOOWMMMMMMMMMMMMMMMMMMMMWklOXO0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0O0dlkWMMMMMMMMMMMMMMMMMMMMWOO0;:KMMMMMMMMMMMMMWNXKx;.,;. ........... .:OWMMMMMMMM
# MMMMMMWKd;'.      ... ;dd:.;kXNNWMMMMMMMMMMMNl.x0xKMMMMMMMMMMMMMMMMMMMMXdxXXOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX00OxxXMMMMMMMMMMMMMMMMMMMMKx0x.lXMMMMMMMMMMMWNNXk;.:dd; ...      ..;o0WMMMMMMMMMM
# MMMMMMMMMWX0kdoooooolc;':do,.;xKNWWMMMMMMMMMNc :0kOMMMMMMMMMMMMMMMMMMMMKdkXXKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKXXkdKMMMMMMMMMMMMMMMMMMMM0k0; cNMMMMMMMMMWWNKx;.,od;';cloooooodk0XWMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMWXxlll;. 'o0XNNWMMMMMMXc 'OkkWMMMMMMMMMMMMMMMMMMMxcd0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0d:xMMMMMMMMMMMMMMMMMMMWkOO' cXMMMMMMWNNX0o' .;lccxXWMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMWKkdc'. .;d0NNNWMMNd'..lOkXMMMMMMMMMMMMMMMMMMWl:dkKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKxd:lNMMMMMMMMMMMMMMMMMMXk0l..'oNMMWNNN0d;. .'cdxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOd,.  .:okKNKo'.. .oOKWMMMMMMMMMMMMMMMMMXcokkKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkkocXMMMMMMMMMMMMMMMMMWK0o. ..'oKNKko:.  .,oOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.   ..'..     .oKNWMMMMMMMMMMMMMMMMX:oOoOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoOo:KMMMMMMMMMMMMMMMMWNKo.     .''..   .:xKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc'. ....     .c0XWMMMMMMMMMMMMMMMN::OldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdlO::NMMMMMMMMMMMMMMMWX0c.     .... ..:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;'',;;,'.  ;kXNMMMMMMMMMMMMMMN:.kdo0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0odk.:NMMMMMMMMMMMMMMNXk,  .',;;,'';lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xc,'',,,'..cONWWMMMMMMMMMMMWc.dOx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0x0d cNMMMMMMMMMMMWWNOc..',;,'.,cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxl;',;'..:xKNWWMMMMMMMMWc 'dxOXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXkxd. cNMMMMMMMMWWNKx:..';,',lx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdo;   .:d0NWWMMMMW0;.cxdd0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXX0ddxc.,0WMMMMWWN0d;.   ;ookKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXNWMMMMMMMMMMMMMW0,  ...'coddxkko,. .,ldOXXKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKXXOdl,. .,okkxddoc.     'OWMMMMMMMMMMMMMWNXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,cdO0KXNWWWWWWWNKk:.  ....','...,;cloool:;:oOOKNNNWMMMMMMMMMMMMMMMMMMMMMMWNNNKOOo:;:looolc;,...','.     .:kKNWWWWWWWNXK0Ooc,cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo;...,;::cllc:;'.                  ..';codc..,;xNNWMMMMMMMMMMMWWWMMMMMMMMWNNx;,..cdoc;'..                  .';:cllc::;,...,o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:'.                ..';:cccc::;'..    ....,d00OKXXXNXXWMMWWMMWXXNNXKX00Kd,....    ..';::cccc:;'..                ..:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdlc:;,,;;:codxO0XNWMMMMMMMWWX0ko:. ...'lkxxd:;d00xxXX0XNKk:cOd;;okxko,... .:ok0XNWMMMMMMMWNX0Oxdoc::;,,;:cldk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMWO,.,:;cc:c,.cxOkdkOdokOkklcko. 'cccl;:;..xWMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxxdxk00KXWMWO,.,:ccdxxd:,lxdodooxkddoooxl.'oxxxc:c,..xWMWNK00kxxxxkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXKK0kdoc;,,,:cclloodxdoocclc..,lolol;cccxlcxkdlcldl:c;coloo;..:lccoodxdoolllc:;,,;cldkOKKKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo,..;;lk0KXXXXXK0Oxdxdl;,:o''kKo,..;;;ldo;:xd;,ldo:;;..'l00;.lc,;coddxO0KXXXXXK0Oo;;..'lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdloxKWMMMMMMMMMMNkc,.'..,.'x0dxl.';::;:::l:,::;::;'.cxdOO;.,..'.':xNWMMMMMMMMMWKkoco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxddx0XWWWNXK0x:.... .',:c:clc;,;c:,,::'.',;c:,;clc:c:,'. .. .,d0KXNNWWX0kdddx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xoooxkkxdxO0k:'.  .',,;,.'c::c',c;,,..'''.:c:c,.';;:,.  ..;x00xddxkkdood0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXXNMMMXd;.';:,'',;cccdkloOl;,':oc:ckxccc:,'';:;'.,oKMMMWXXKKXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;lool:,.',;cxxooo:;;::;:llxxl:;'.';cooo;lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkdOK0d:'.':;.,;;,,::c:'',;,.,:,.':oOK0dxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdccxKko;','.,l:,,,,:;'';l;.',',lkKkl:o0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkOKXKKOl;;,cc;c'.,,..;l,;;cOKKXK0k0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKK0kx0KOxoc;..',. ......,cldkK0kx0KKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl:l;.'ck0Xx.      .     .lXKkl,.,ccc0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.:d:. .,xKl .....  ... ;KO:. .,dc.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'.ckl.  ;0O'.;,.. .::..xKc.  :kl..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk..,oc. ,xO: ,c'  :x: 'dx;  :o;..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c'.''..cxc..c;..:l' ';'..''..:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkc..';:l:. :c.':;. ,:;;'..:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'.;ccc. :l.,:,. ;lc;.'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo''cc,. ;c.,:.. ':c..lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.';'. ':'::.  ';,.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'...  ...',.. ....xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;...';'.  ';,'...'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc...,::::::c:;...:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkl:.,clccllclll;.;cdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxcl:,;,..'...,;,;lcdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o:'...      .';lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXk:. ....    ,xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;,,;',,,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOollxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM



print('Hello World')

print("I've already add this line, then I commit to Github")